version: '3.7'

services:
  web:
    build: .
    command: sh -c "
        python manage.py collectstatic --noinput
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "587:587"
    expose:
      - 587
    env_file:
        - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.3-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: hello_django
      POSTGRES_USER: hello_django
      POSTGRES_DB: hello_django
    volumes:
      - dj_hero_vol:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
volumes:
  dj_hero_vol:
