version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    ports:
      - 80:80
    env_file:
        - ./.env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: hello_django
      POSTGRES_USER: hello_django
      POSTGRES_DB: hello_django_prod
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
