# Generated by Django 3.1.2 on 2021-01-14 10:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210114_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
